create sequence hibarnate_sequence start 1 increment 1;

create table author (
                        author_id int8 generated by default as identity,
                        date_of_birth date,
                        full_name varchar(255),
                        primary key (author_id)
);

create table author_book (
                             author_id int8 not null,
                             book_id int8 not null,
                             primary key (author_id, book_id)
);

create table book (
                      book_id int8 generated by default as identity,
                      page_count int4,
                      price int4,
                      release_year date,
                      title varchar(255),
                      publisher_id int8,
                      primary key (book_id)
);

create table book_genre (
                            book_id int8 not null,
                            genre_id int8 not null,
                            primary key (book_id, genre_id)
);

create table genre (
                       genre_id int8 generated by default as identity,
                       genre_name varchar(255),
                       primary key (genre_id)
);

create table publisher (
                           publisher_id int8 generated by default as identity,
                           name varchar(255),
                           primary key (publisher_id)
);

create table users (
                       user_id int8 generated by default as identity,
                       login varchar(255),
                       password varchar(255),
                       role varchar(255),
                       blocked bool,
                       primary key (user_id)
);



alter table if exists author_book
    add constraint fk_autboo_on_books
    foreign key (book_id)
    references book;

alter table if exists author_book
    add constraint fk_autboo_on_author
    foreign key (author_id)
    references author;

alter table if exists book
    add constraint FK_BOOK_ON_PUBLISHER
    foreign key (publisher_id)
    references publisher;

alter table if exists book_genre
    add constraint fk_boogen_on_genre
    foreign key (genre_id)
    references genre;

alter table if exists book_genre
    add constraint fk_boogen_on_books
    foreign key (book_id)
    references book;

